# Netlify configuration file
# This file should be in the root of your project

[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "/"
  
  # Directory with the serverless functions
  functions = "netlify/functions"

# Properly configured redirect for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
